---
- name: Install Remote Engine
  hosts: all
  
  vars:
    ansible_user: azureuser
    ansible_password: Temporary123
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    jdk_package: openjdk11
    java_major_version: 11.0.16
    java_minor_version: 8
  
  tasks:

  - name: Install Java
    win_chocolatey:
      name: "{{ jdk_package }}"
      state: present
      version: "{{ java_major_version }}"

  - name: Set Java_home
    win_environment:
      state: present
      name: JAVA_HOME
      value: 'c:\Program Files\OpenJDK\openjdk-{{ java_major_version }}_{{ java_minor_version }}'
      level: machine

  - name: Add Java to path
    win_path:
      elements:
        - 'c:\program files\java\OpenJDK\openjdk-{{ java_major_version }}_{{ java_minor_version }}\bin'
  - name: Enable firewall for Domain, Public and Private profiles
    community.windows.win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public
    tags: disable_firewall

  - name: Copy Talend Remote Engine file
    win_copy:
      src: '/home/ansible/Talend-RemoteEngine-V{{ tre_version }}.zip'
      dest: C:\Users\azureuser
  
  - name: Unzip a Talend Remote Engine file
    community.windows.win_unzip:
      src: 'C:\Users\azureuser\Talend-RemoteEngine-V{{ tre_version }}.zip'
      dest: C:\Users\azureuser\
  
  - name: Copy Talend Remote Engine file
    win_copy:
      src: /home/ansible/org.talend.ipaas.rt.pairing.client.cfg
      dest: 'C:\Users\azureuser\Talend-RemoteEngine-V{{ tre_version }}\etc\org.talend.ipaas.rt.pairing.client.cfg'
  
  - name: Copy Talend Remote Engine file
    win_copy:
      src: /home/ansible/preauthorized.key.cfg
      dest: 'C:\Users\azureuser\'
  
  - name: Change configuration files for Talend
    community.windows.win_lineinfile:
      path: 'C:\Users\azureuser\Talend-RemoteEngine-V{{ tre_version }}\etc\preauthorized.key.cfg'
      regexp: 'remote.engine.pre.authorized.key'
      line: "remote.engine.pre.authorized.key = {{ lookup('file','/home/ansible/preauthorized.key.cfg') }}"
  
  - name: Change jobserver config file for Talend Sudio connection
    community.windows.win_lineinfile:
      path: 'C:\Users\azureuser\Talend-RemoteEngine-V{{ tre_version }}\etc\org.talend.remote.jobserver.server.cfg'
      regexp: "{{ item.var1 }}"
      line: "{{ item.var2 }}"
    with_items: 
      - { var1: "org.talend.remote.jobserver.server.TalendJobServer.COMMAND_SERVER_HOST=*", var2: org.talend.remote.jobserver.server.TalendJobServer.COMMAND_SERVER_HOST=0.0.0.0 }
      - { var1: "org.talend.remote.jobserver.server.TalendJobServer.FILE_SERVER_HOST=*", var2: org.talend.remote.jobserver.server.TalendJobServer.FILE_SERVER_HOST=0.0.0.0} 
        
  - name: Install Remote Talend Engine
    ansible.windows.win_powershell: 
      script: |
        cd C:\Users\azureuser\Talend-RemoteEngine-V"{{ tre_version }}"\bin
        echo "feature:install wrapper `nwrapper:install -n talend-remote-engine `nsleep 60 `nlogout" | .\trun.bat
        .\talend-remote-engine-service.bat install
    register: result 
    until: result is not failed
    delay: 10 
    retries: 5 
  - name: Set service startup mode to auto and ensure it is started
    ansible.windows.win_service:
      name: 'talend-remote-engine'
      start_mode: auto
      state: started


