- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  
  - include_vars: /home/ansible/vars/ubuntu_vars.yaml
  - set_fact:
        random_name: "{{ ansible_date_time.epoch }}"

  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{vm_resource_group}}-{{ random_name }}"
      location: "{{ vm_location }}"
  - name: Add resource group to inventory
    ansible.builtin.lineinfile:
      path: /home/ansible/ubuntu/azure_rm.yaml 
      regex: "- ubuntu*"
      line: "- ubuntu-{{ random_name }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{vm_resource_group}}-{{ random_name }}"
      name: "{{ virtual_network }}-{{ random_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{vm_resource_group}}-{{ random_name }}"
      name: "{{ virtual_subnet }}-{{ random_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtual_network }}-{{ random_name }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{vm_resource_group}}-{{ random_name }}"
      #allocation_method: Static
      name: "{{ vm_public_ip }}-{{ random_name }}"
  - name: Create Network Security Group that allows SSH and Tallend Cloud
    azure_rm_securitygroup:
      resource_group: "{{vm_resource_group}}-{{ random_name }}"
      name: "{{ vm_security_group }}-{{ random_name }}"
      rules: 
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: Talend_port
          protocol: Tcp
          destination_port_range: 8043
          access: Allow
          priority: 1000
          direction: Inbound
        - name: Talend_command_port
          protocol: Tcp
          destination_port_range: 8003
          access: Allow
          priority: 1003
        - name: Talend_file_port
          protocol: Tcp
          destination_port_range: 8004
          access: Allow
          priority: 1004
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{vm_resource_group}}-{{ random_name }}"
      name: "{{ vm_network_interface }}-{{ random_name }}"
      virtual_network: "{{ virtual_network }}-{{ random_name }}"
      subnet: "{{ virtual_subnet }}-{{ random_name }}"
      public_ip_name: "{{ vm_public_ip }}-{{ random_name }}"
      security_group: "{{ vm_security_group }}-{{ random_name }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{vm_resource_group}}-{{ random_name }}"
      name: "{{ vm_name }}-{{ random_name }}"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ vm_username }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ lookup('file', '/home/ansible/id_rsa.pub') }}"
      network_interfaces: "{{ vm_network_interface }}-{{ random_name }}"
      image:
        offer: "{{ os_offer }}"
        publisher: "{{ os_publisher }}"
        sku: "{{ vm_sku }}"
        version: "{{ os_version }}"
  
  - name: Get facts for one Public IP
    azure_rm_publicipaddress_info:
      resource_group: "{{vm_resource_group}}-{{ random_name }}"
      name: "{{ vm_public_ip }}-{{ random_name }}"
    register: publicipaddresses

  - name: set public ip address fact
    set_fact: publicipaddress="{{ publicipaddresses | json_query('publicipaddresses[0].ip_address')}}"

  - name: Save Public IP to file 
    ansible.builtin.copy:
      dest: /home/ansible/ubuntuPublicIP.txt 
      content: "{{ publicipaddress }}"
  
  
  